@echo off
rem This file has been generated by genproj.tcl script from CASROOT/adm/templates/msvc.bat

set "ENVBAT=D:\occ\opencascade-install\env.bat"
rem Setup environment
call "%ENVBAT%" vc143 win64 %3

rem Define path to project file
set "PRJFILE=.\SheetFlatten.sln"

rem Launch Visual Studio - either professional (devenv) or Express, as available
start "" "%DevEnvDir%\devenv.exe" "%PRJFILE%"


rem start "" "%DevEnvDir%\devenv.exe"